## numpy 배열

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
print(a + a)

[2 4 6 8]


## 일반 배열

In [3]:
b = [1,2,3,4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


## 이중 배열(행렬)

In [4]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


## 삼중 배열(행렬)

In [5]:
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


## 배열의 모양(Shape)

In [6]:
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(b)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [7]:
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


## 전치연산(Transpose)

In [8]:
a = np.array([[1],[2],[3],[4]])
print(a) #shape = (4,1)
print(a.T) #shape = (1,4)

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [9]:
a = np.array([1,2,3,4])
print(a)
print(a.T)

[1 2 3 4]
[1 2 3 4]


## Reshape

In [10]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.reshape(3,-1))
print(a.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [11]:
a = np.array([1,2,3,4])
print(a)
print(a.T)
print(a.reshape(-1,1))

[1 2 3 4]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


## 배열 인덱싱

In [12]:
a = np.array([10,20,30,40,50,60])
print(a)
b = a[[4,2,0]]
print(b)

[10 20 30 40 50 60]
[50 30 10]


In [13]:
idx = np.arange(0, len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

[0 1 2 3 4 5]
[1 4 2 0 3 5]
[20 50 30 10 40 60]
