In [1]:
import numpy as np

Useful documents link :
1. https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.matrix.html
1. https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.det.html
1. https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html

## How to create matrix?
1. `numpy.matrix` : Good for mathematical sense
1. `numpy.array` : Good for practical sense

In [8]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
x = np.matrix('1;2;3;4')
print(A)
print(x)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]


In [3]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
x = np.array([1,2,3,4])
print(A)
print(x)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]


## Example 01-1 (Matrix-Vector Multiplication)
Write code for the follwoing problem.
\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [5]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
x = np.matrix('1;2;3;4')
b = np.zeros((4,1))
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO 1
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[[ 15.]
 [ 19.]
 [ 26.]
 [ 44.]]


In [13]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO 2
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[15 19 26 44]


## Example 01-2 (Matrix-Vector Multiplication)
Write code for the follwoing problem using `numpy`.
\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [14]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
print(A)
x = np.matrix('1;2;3;4')
print(x)

# TODO 3
b = A*x
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[[1]
 [2]
 [3]
 [4]]
[[15]
 [19]
 [26]
 [44]]


In [16]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
print(A)
x = np.array([1,2,3,4])
print(x)
b = np.array([0,0,0,0])
# TODO 4

b = np.dot(A,x)
print(b)

b = np.matmul(A,x)
print(b)

[[1 4 2 0]
 [9 5 0 0]
 [4 0 2 4]
 [6 1 8 3]]
[1 2 3 4]
[15 19 26 44]
[15 19 26 44]


#### Remark
While `np.array` can be used for matrix/vector multiplication, in this lecture, we prefer `np.matrix`, since `np.matrix` is more intuitive for users in the view of linear algebra. You can see sample code to show `np.matrix`'s convience.


In [11]:
A = np.array([[1, 4, 2, 0],[9, 5, 0, 0], [4, 0, 2, 4],[6, 1, 8, 3]])
x = np.array([1, 2, 3, 4])

In [12]:
A*x

array([[ 1,  8,  6,  0],
       [ 9, 10,  0,  0],
       [ 4,  0,  6, 16],
       [ 6,  2, 24, 12]])

In [17]:
np.dot(A,x)

array([15, 19, 26, 44])

In [18]:
np.dot(x,A)

array([55, 18, 40, 24])

## Example 02-1 (Matrix-Vector Multiplication)
Write code for the follwoing problem.
\begin{equation}
\begin{bmatrix}
4 & 5 & 2 & 1 \\
2 & 3 & 8 & 0 \\
1 & 0 & 7 & 2
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [21]:
A = np.matrix('4, 5, 2, 1; 2, 3, 8, 0; 1, 0, 7, 2')
x = np.matrix('1;2;3;4')
print(A*x)
m = 3
n = 4
b = np.zeros((m,1))
# TODO 5
for i in range(0, m):
    val = 0
    for j in range(0,n):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[[24]
 [32]
 [30]]
[[ 24.]
 [ 32.]
 [ 30.]]


In [23]:
A = np.array([[4, 5, 2, 1], [2, 3, 8, 0], [1, 0, 7, 2]])
x = np.array([1,2,3,4])
print(np.matmul(A,x))
m = 3
n = 4
b = np.zeros(m)
# TODO 5
for i in range(0, m):
    val = 0
    for j in range(0,n):
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[24 32 30]
[ 24.  32.  30.]


## Example 02-2 (Matrix-Vector Multiplication)
Write code for the follwoing problem using `numpy`.
\begin{equation}
\begin{bmatrix}
4 & 5 & 2 & 1 \\
2 & 3 & 8 & 0 \\
1 & 0 & 7 & 2
\end{bmatrix}
\begin{bmatrix}
1\\2\\3\\4
\end{bmatrix}=?
\end{equation}

In [24]:
A = np.matrix('4, 5, 2, 1; 2, 3, 8, 0; 1, 0, 7, 2')
x = np.matrix('1;2;3;4')

In [25]:
A*x

matrix([[24],
        [32],
        [30]])

In [26]:
A = np.array([[4, 5, 2, 1], [2, 3, 8, 0], [1, 0, 7, 2]])
x = np.array([1,2,3,4])

In [27]:
np.dot(A,x)

array([24, 32, 30])

In [28]:
np.matmul(A,x)

array([24, 32, 30])