In [1]:
import numpy as np

## Example 01 (Soution of the Linear System)
1. Determine if this linear system has a solution.
1. Write code to find a solution, $x$, of the following linear system code using `numpy`.

\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [2]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
b = np.matrix('15;19;26;44')

In [3]:
np.linalg.det(A)

853.99999999999955

In [4]:
x = np.linalg.solve(A, b)
x

matrix([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.]])

In [5]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
b = np.array([15,19,26,44])

In [6]:
np.linalg.det(A)

853.99999999999955

In [7]:
x = np.linalg.solve(A,b)
x

array([ 1.,  2.,  3.,  4.])

## Example 02(Not invertible Lineary System)
\begin{align}
x_1 + x_2 &= 2\\
2x_1 + 2x_2 &= 3
\end{align}
, that is, 
\begin{equation}
\begin{bmatrix}
1 & 1 \\
2 & 2 
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2
\end{bmatrix}=
\begin{bmatrix}
2\\3
\end{bmatrix}
\end{equation}


In [8]:
A = np.matrix('1, 1; 2, 2')
b = np.matrix('2;3')
np.linalg.det(A)

0.0

In [9]:
x = np.linalg.solve(A, b)

LinAlgError: Singular matrix

The matrix $A$ whose determinant is zero called `Singular matrix`.(`Singular`라는 말 그대로, 방정식이 풀리지 않는 `이상한` 매트릭스.)

## Example 04 (Soution of the Linear System)
Write code to find a solution, $x$, of the following linear system code using Jacobi method.
\begin{equation}
\begin{bmatrix}
10 & 4 & 2 & 0 \\
9 & 15 & 0 & 0 \\
4 & 0 & 12 & 4 \\
6 & 1 & 8 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [10]:
A = np.matrix('10, 4, 2, 0; 9, 15, 0, 0; 4, 0, 12, 4; 6, 1, 8, 13')
b = np.matrix('15;19;26;44')

In [11]:
D = np.diag(np.diag(A))
R = A - D

In [12]:
invD = np.matrix(np.diag(1 / np.diag(A)))
invD

matrix([[ 0.1       ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.06666667,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.08333333,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.07692308]])

- TODO 1 : $x^{(k+1)} = D^{-1} (b - Rx^{(k)})$

In [16]:
MaxIter = 10
x0 = np.matrix('1;1;1;1')
for it in range(MaxIter):
    # TODO 1
    x1 = invD * (b - R * x0)
    x0 = x1

In [17]:
x0

matrix([[ 1.01603595],
        [ 0.65583037],
        [ 1.09652471],
        [ 2.18615955]])

In [18]:
np.linalg.solve(A,b)

matrix([[ 1.01814882],
        [ 0.65577737],
        [ 1.09770115],
        [ 2.18874773]])

## Example 05 (Soution of the Linear System)
Write code to find a solution, $x$, of the following linear system code using Jacobi Methd.

\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [19]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3')
b = np.matrix('15;19;26;44')

In [20]:
D = np.diag(np.diag(A))
R = A - D

In [21]:
invD = np.matrix(np.diag(1 / np.diag(A)))
invD

matrix([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.2       ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.5       ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.33333333]])

- TODO 2 : $x^{(k+1)} = D^{-1} (b - Rx^{(k)})$ with for loop

In [25]:
MaxIter = 10
x0 = np.matrix('1;1;1;1')
# TODO 2
for it in range(MaxIter):
    x1 = invD * (b - R * x0)
    x0 = x1

In [26]:
x0

matrix([[-1408849.0754963 ],
        [ -722351.49788444],
        [-1745683.03095967],
        [-1931370.50097778]])

In [27]:
np.linalg.solve(A, b)

matrix([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.]])

## Example 06 (Soution of the Linear System)
Write code to find a solution, $x$, of the following linear system code using CG method.
\begin{equation}
\begin{bmatrix}
10 & 4 & 2 & 6 \\
4 & 15 & 0 & 1 \\
2 & 0 & 12 & 4 \\
6 & 1 & 4 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

If you prefer `np.Matrix`,

- TODO 3 : $\alpha_k = \frac{r_k^T r_k}{p_k^T A p_k}$
- TODO 4 : $\beta_k = \frac{r_{k+1}^T r_{k+1}}{r_k^T r_k}$

In [31]:
A = np.matrix('10, 4, 2, 6; 4, 15, 0, 1; 2, 0, 12, 4; 6, 1, 4, 13')# Symmetric
b = np.matrix('15;19;26;44')
x0 = np.matrix('1;1;1;1')
r0 = b - A*x0
p0 = r0
MaxIter = 4
for it in range(MaxIter):
    # TODO 3
    a0 = r0.T * r0 / (p0.T * A * p0)


    x1 = x0 + a0[0,0] * p0
    r1 = r0 - a0[0,0] * A * p0
    
    if np.linalg.norm(r1) < 1E-8:
        break
    # TODO 4
    b0 = r1.T * r1 / (r0.T * r0)
    p1 = r1 + b0[0,0] * p0

    r0 = r1
    p0 = p1
    x0 = x1

print(x0)

[[-1.45345289]
 [ 1.41651813]
 [ 1.21974559]
 [ 3.5706635 ]]


In [32]:
np.linalg.solve(A,b)

matrix([[-1.45290942],
        [ 1.4160168 ],
        [ 1.21835633],
        [ 3.57138572]])

If you prefer `np.array`

- TODO 5 : $\alpha_k = \frac{r_k^T r_k}{p_k^T A p_k}$

In [33]:
A = np.array([[10,  4,  2,  6],[ 4, 15,  0 , 1], [ 2,  0, 12,  4], [ 6,  1,  4, 13]])
b = np.array([15, 19, 26, 44])
x0 = np.array([1, 1, 1, 1])
r0 = b - np.dot(A,x0)
p0 = r0
MaxIter = 4
for it in range(MaxIter):
    # TODO 5
    a0 = np.dot(r0, r0) / np.dot(p0, np.matmul(A, p0))
    x1 = x0 + a0 * p0
    r1 = r0 - a0 * np.dot(A, p0)

    if np.linalg.norm(r1) < 1E-8:
        break

    b0 = np.dot(r1, r1) / np.dot(r0, r0)
    p1 = r1 + b0 * p0

    r0 = r1
    p0 = p1
    x0 = x1

print(x0)

[-1.45345289  1.41651813  1.21974559  3.5706635 ]


In [34]:
np.linalg.solve(A,b)

array([-1.45290942,  1.4160168 ,  1.21835633,  3.57138572])

## Example 07 (Soution of the Linear System)
Write code to find a solution, $x$, of the following linear system code using CG method.
\begin{equation}
\begin{bmatrix}
1 & 4 & 2 & 0 \\
9 & 5 & 0 & 0 \\
4 & 0 & 2 & 4 \\
6 & 1 & 8 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [35]:
A = np.matrix('1, 4, 2, 0; 9, 5, 0, 0; 4, 0, 2, 4; 6, 1, 8, 3') # not symmetric
b = np.matrix('15;19;26;44')

- TODO 6 : $r_{k+1} = r_k - \alpha_k A p_k$

In [44]:
x0 = np.matrix('1;1;1;1')
r0 = b - A*x0
p0 = r0
MaxIter = 100
for it in range(MaxIter):
    a0 = r0.T * r0 / (p0.T * A * p0)
    x1 = x0 + a0[0,0] * p0
    # TODO 6
    r1 = r0 - a0[0,0] * A*p0
    
    if np.linalg.norm(r1) < 1E-8:
        break
    
    b0 = r1.T * r1 / (r0.T * r0)
    p1 = r1 + b0[0,0] * p0

    r0 = r1
    p0 = p1
    x0 = x1
print(x0)

[[ 1.04311773]
 [ 1.96017801]
 [ 2.92927628]
 [ 3.97105801]]


In [45]:
np.linalg.solve(A,b)

matrix([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.]])